apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
    - name: redis-db
      image: redis:7-alpine
      command:
        - "redis-server"
      args:
        - "--logLevel debug"
      ports:
        - name: def-red-port
        - containerPort: 6379
          hostPort: 6379
