# https://kind.sigs.k8s.io/docs/user/configuration/
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: k8s-dd-cluster
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
featureGates:
  GracefulNodeShutdown: true
  HPAContainerMetrics: true
  HPAScaleToZero: true
  OpenAPIV3: true
nodes:
  - role: control-plane
    labels:
      role: cp
    image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
  - role: worker
    labels:
      role: wk
    image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
  - role: worker
    labels:
      role: wk
    image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
  - role: worker
    labels:
      role: wk
    image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
